name: Weekly Calendar Update

on:
  schedule:
    - cron: '0 12 * * 1'  # 每周一 UTC 时间 12:00（美东时间上午 8 点）
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies and generate .ics
        run: |
          pip install ics pytz
          python generate_calendar.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add short_term_trading.ics
          git commit -m "Auto-update .ics for this week" || echo "No changes to commit"
          git push
